[programs.localnet]
solana_twitter = "F1k3zJSy6gqFUY3CTv3HZeJ9S6QkeEnctcPiKaLKc96U"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/turtle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello World'"